---
- name: Playbook for vpc
  hosts: localhost
  tasks:
  - name: VPC for class
    ec2_vpc_net:
      name: TaskVPC
      cidr_block: 10.10.0.0/16
      region: ca_central-1
      tags:
        Class: Ansible
        Task: VPC