---
- name: Playbook for vpc
  hosts: localhost
  tasks:


    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: ca-central-1
        filters:
         "tag:Task": VPC
      register: VPC1 

      
    - name: Create IGW
      ec2_vpc_igw:
        region: ca-central-1
        vpc_id: "{{VPC1.vpc[0].vpc_id}}"
        state: present
      register: igw