---
- name: Playbook for VPC
  hosts: localhost
  tasks:
    - name: VPC for class
      ec2_vpc_net:
        name: TaskVPC
        cidr_block: 10.0.0.0/16
        region: ca-central-1
        tags:
          Class: Ansible
          Task: VPC