---
- name: Playbook for Provisioning
  hosts: localhost 
  become: yes
  become_method: sudo
  tasks: 
    - ec2:
        key_name:"{{key_name}}"
        instance_type: "{{instance_type}}"
        image: ami-033e6106180a626d0
        count: "{{count}}"
        vpc_subnet_id: "{{vpc_subnet_id}}"
        assign_public_ip: yes
        region: "{{region}}"