---
- name: Playbook for sec groups
  hosts: localhost
  gather_facts: no 
  tasks:


    - name: Collect VPC info
      ec2_vpc_net_facts:
        region: ca-central-1
        filters:
         "tag:Task": VPC
      register: VPC1   


    - name: Sec 
      ec2_group:
        name: SecGroup
        description: Sec Group 1 for VPC
        vpc_id: "{{VPC1.vpc[0].vpc_id}}"
        region: ca-central-1
        rules:
         - proto: tcp
           ports:
           - 80
           - 22
           cidr_ip: 0.0.0.0/0
          
