---
- name: Playbook for vpc provision module
  hosts: localhost 
  become: yes
  become_method: sudo
  tasks:
    - ec2_vpc_net:
        name: Module_dev2
        cidr_block: 10.10.0.0/16
        region: us-east-2
        tags:
          module: ec2_vpc_net
          this: works
        tenancy: dedicated