---
- name: Playbook for create private subnet for database servers
  hosts: localhost 
  become: yes
  become_method: sudo
  tasks:
    - ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc_id }}"
        cidr: 10.0.1.16/28
        resource_tags:
          Name: Database Subnet
          register: database_subnet
